config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :posts
  resources :projects
  resources :contacts, only: [:new, :create]
  get 'welcome/index'
  get 'bot' => 'welcome#bot'
  get 'ask_newton', to: 'application#ask_newton'
  root 'welcome#index'

  get '*path' => redirect('/')

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true

  def headers
  	{
	  	:subject => "Contact Form",
	  	:to => "mackenzie@unicasts.com",
	  	:from => %("#{name}" <#{email}>)
	  }
	end
end

app/models/post.rb
class Post < ApplicationRecord
	extend FriendlyId
  	friendly_id :title, use: :slugged
end

app/models/project.rb
class Project < ApplicationRecord
	extend FriendlyId
  	friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def ask_newton
  	reaction = NEWTONBOT.get_reaction(params[:query])
    render json: { response: reaction.present? ? reaction : "I'm sorry, I don't understand that :(" }
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(params[:contact])
		@contact.request = request
		if @contact.deliver
			flash.now[:error] = nil
		else
			flash.now[:error] = 'Cannot send message.'
			render :new
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@posts = Post.all.order("created_at desc").paginate(page: params[:page], per_page: 2)
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new post_params

		if @post.save
			redirect_to @post, notice: "Post created"
		else
			render 'new', notice: "Something is wrong"
		end
	end

	def show 
	end

	def edit 
	end

	def update 
		if @post.update post_params
			redirect_to @post, notice: "Updated"
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to posts_path
	end

	private

	def post_params
		params.require(:post).permit(:title, :content, :slug)
	end

	def find_post
		@post = Post.friendly.find(params[:id])
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :find_project, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@projects = Project.all.order("created_at desc")
	end

	def new
		@project = Project.new
	end

	def show
	end

	def edit

	end

	def create 
		@project = Project.new project_params
		if @project.save
			redirect_to @project, notice: "Project created"
		else
			render 'new', notice: "Failed"
		end
	end

	def update
		if @project.update project_params
			redirect_to @project, notice: "Updated"
		else
			render 'edit'
		end
	end

	def destroy
		@project.destroy
		redirect_to projects_path
	end

	private
	def project_params
		params.require(:project).permit(:title, :description, :link, :slug)
	end

	def find_project
		@project = Project.friendly.find(params[:id])
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :slug)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@posts = Post.all.limit(3).order("created_at desc")
		@projects = Project.all.limit(3).order("created_at desc")
	end

	def bot

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end
	def markdown(content)
		renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
		options = {
			autolink: true,
      no_intra_emphasis: true,
      disable_indented_code_blocks: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
		}
		Redcarpet::Markdown.new(renderer, options).render(content).html_safe
	end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<h1 id="page_title">Say Hello</h1>

	<div class="skinny_wrapper wrapper_padding">
		<h1>Thank you for your message!</h1>
		<p>I'll get back to you soon.</p>
	</div>

app/views/contacts/new.html.erb
<h1 id="page_title">Say Hello</h1>

	<div class="skinny_wrapper wrapper_padding">
		<%= form_for @contact do |f| %>
			<%= f.label :name %><br>
			<%= f.text_field :name, required: true %><br>

			<br>

			<%= f.label :email %><br>
			<%= f.text_field :email, required: true %><br>

			<br>

			<%= f.label :message %><br>
			<%= f.text_area :message, as: :text %><br>

			<div class="hidden">
				<%= f.label :nickname %><br>
			<%= f.text_field :nickname, hint: "leave this field blank" %><br>
			</div>

			<%= f.submit 'Send Message', class: "button" %>
		<% end %>
		
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NerdyNewton - Foodie, Developer</title>
	<link href="https://fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<header id="main_navigation" class="clearfix">
		<a href="/" class="name">Nerdy Newton</a>
		<nav>
			<%= link_to "Blog", posts_path %>
			<%= link_to "Projects", projects_path %>
			<%= link_to "Say Hello", new_contact_path %>
			<% if user_signed_in? %>
				<%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
			<% end %>
		</nav>
	</header>

	<% if notice %>
		<p class="notice"><%= notice %></p>
	<% elsif alert %>
       	<p class="alert"><%= alert %></p>
	<% end %>

    <%= yield %>
    <footer id="main_footer">
		<p class="copyright">&copy;2016 Nerdy Newton</p>
		<nav>
			<a href="https://twitter.com/newtonlaw18" target="blank"><i class="fa fa-twitter"></i></a>
			<a href="https://www.facebook.com/newtonlaw18" target="blank"><i class="fa fa-facebook" aria-hidden="true"></i></a>
			<a href="https://github.com/newtonlaw18" target="blank"><i class="fa fa-github" aria-hidden="true"></i></a>
		</nav>
	</footer>
  </body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = '//nerdy-newton.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                                

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
		<ul>
			<% @post.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<%= f.label :title %> <br>
	<%= f.text_field :title %>

	<%= f.label :content, "Write your article here" %> <br>
	<%= f.text_area :content %>

	<%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<div class="skinny_wrapper wrapper_padding">
	<h1>Edit Blogpost</h1>
	<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<h1 id="page_title">Stuff I've written</h1>

	<div id="posts_wrapper" class="skinny_wrapper">
		<% @posts.each do |post| %>
		<div class="post">
			<p class="date"><%= post.created_at.strftime('%A, %B %d') %></p>
			<h2><%= link_to post.title, post %>
			</h2>
			<hr>
		</div>	
		<% end %>			
	</div>

	<%= will_paginate @posts %>

app/views/posts/new.html.erb
<div class="skinny_wrapper wrapper_padding">
	<h1>New Blogpost</h1>
	<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
		<header>
			<p class="date"><%= @post.created_at.strftime('%A, %B %d') %></p>
			<h1><%= @post.title %></h1>
			<hr>
		</header>

		<div id="content">
			<%= markdown @post.content %>
		</div>

		<% if user_signed_in? %>
			<div id="admin_links"> 
			<%= link_to "Edit Blogpost", edit_post_path(@post) %>
			<%= link_to "Delete Blogpost", post_path(@post), method: :delete, data: { confirm: "Are you sure?"} %>
			</div>
		<% end %>

		<hr>

		<div id="share_box">
			<p>Share The Title</p>
			<a onclick="javascript:window.open('http://twitter.com/share?text=<%= @post.title %> by @newtonlaw18 - &amp;url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-twitter"></i></a>
			
			 <a onclick="javascript:window.open('http://www.facebook.com/sharer.php?u=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-facebook"></i></a>
    		<!-- Google Plus -->
    		<a onclick="javascript:window.open('https://plus.google.com/share?url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-google-plus"></i></a>

		</div>

		<hr>
		<%= render 'disqus' %>
	</div>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
	<% if @project.errors.any? %>
		<h2><%= pluralize(@project.errors.count, "error") %> prevented this project from saving:</h2>
		<ul>
			<% @project.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<%= f.label :title %> <br>
	<%= f.text_field :title %>

	<%= f.label :description, "Write your description here" %> <br>
	<%= f.text_area :description %>

	<%= f.label :link %> <br>
	<%= f.text_field :link %>

	<%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<div class="skinny_wrapper wrapper_padding">
	<h1>Edit Project</h1>
	<%= render 'form' %>
</div>

app/views/projects/index.html.erb
<h1 id="page_title">Stuff I've built</h1>

	<div id="posts_wrapper" class="skinny_wrapper">
		<% @projects.each do |project| %>
		<div class="post">
			<p class="date"><%= project.created_at.strftime('%A, %B %d') %></p>
			<h2><%= link_to project.title, project %>
			</h2>
			<hr>
		</div>	
		<% end %>			
	</div>

app/views/projects/new.html.erb
<div class="skinny_wrapper wrapper_padding">
	<h1>New Project</h1>
	<%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
	<header>
		<p class="date"><%= @project.created_at.strftime('%A, %B %d') %></p>
		<h1><%= @project.title %></h1>
		<hr>
	</header>

	<div id="content">
		<%= markdown @project.description %>

		<div class="button_wrapper">
			<a href="<%= @project.link %>" class="project_button" target="_blank">Visit <%= @project.title %> </a>
		</div>
	</div>

	<% if user_signed_in? %>
			<div id="admin_links"> 
			<%= link_to "Edit Project", edit_project_path(@project) %>
			<%= link_to "Delete Project", project_path(@project), method: :delete, data: { confirm: "Are you sure?"} %>
			</div>
		<% end %>

	<hr>

</div>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :slug %>
    <%= f.text_field :slug %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.slug %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @user.slug %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/bot.html.erb
<div class="skinny_wrapper wrapper_padding">
	<h1>Bot</h1>
	<p id="newton-response"></p>
	<input type="text" id="query" placeholder="Ask me anything">
	<!-- <button id="ask_newton_now">Enter</button> -->
</div>

app/views/welcome/index.html.erb
<div class="wrapper wrapper_padding clearfix">
		<div class="col-1 about homepage_content">
			<h2>About</h2>
			<hr>
			<p>I'm a designer &amp; developer living in Colorado Springs, Colorado. 
			</p>
			<p>By day I work as a front-end dev / designer at Precision Nutrition, by night I teach how to design &amp; code rails applications at <a href='#'>Unicasts</a>.
			</p>
			<p>You can find me speaking in 140 characters in Twitter, swooshing some pixels on Dribble, and sharing some code on Github. 
			</p>
		</div>

		<div class="col-2 homepage_content">
			<h2>Stuff I've written</h2>
			<hr>
			<% @posts.each do |post| %>
				<h3><a href="#"><%= link_to post.title, post %></a></h3>
				<p class="date"><%= post.created_at.strftime("%A, %b %d") %></p>
			<% end %>
		</div>

		<div class="col-3 homepage_content">
			<h2>Stuff I've built</h2>
			<hr>
			<% @projects.each do |project| %>
				<h3><a href="#"><%= link_to project.title, project %></a></h3>
				<p class="date"><%= project.created_at.strftime("%A, %b %d") %></p>
			<% end %>
		</div>
	</div>